<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Produtos</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link link-secondary" aria-current="page" href="/">Cadastro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link-secondary" href="/products">Consulta</a>
                    </li>
                </ul>
            </div>

            <div class="col-9">
                <div class="row">
                    <h2 class="my-2">Cadastro de Produtos</h2>
                </div>

                <div class="row">
                    <form action="/insert" method="post" enctype="multipart/form-data">
                        <fieldset>
                            <legend>Cadastre produtos usando arquivos com a extensão: .json ou .xml</legend>

                            <div class="mb-3">
                                <label for="productRegisterFile" class="form-label">Arquivo ... </label>
                                <input class="form-control" type="file" id="productRegisterFile" name="productRegisterFile">
                            </div>

                            <button type="submit" class="btn btn-secondary">Enviar</button>
                        </fieldset>
                    </form>
                </div>
            </div>

        </div>
    </div>
</body>
</html>