<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consulta de Produtos</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link link-secondary" aria-current="page" href="/">Cadastro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link-secondary" href="/products">Consulta</a>
                    </li>
                </ul>
            </div>

            <div class="col-9">
                <div class="row">
                    <h2 class="my-2">Consulta de Produtos</h2>
                </div>

                <div class="row">
                   <table class="table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Tags</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>123</td>
                                <td>Produto #1</td>
                                <td>festa, balada, delicado</td>
                            </tr>

                            <?php if ($products) : ?>

                                <?php foreach ($products as $product) :?>
                                    <tr>
                                        <?php foreach ($product as $attribute => $value) :?>

                                            <?php if (is_array($value)) : ?>

                                                <?php $labels = array_map(function ($tags) {
                                                    return ucfirst($tags['label']);
                                                }, $value) ?>

                                                <?php $value = implode(', ', $labels); ?>

                                            <?php endif ; ?>

                                            <td>
                                                <?php echo $value ?>
                                            </td>

                                        <?php endforeach ; ?>
                                    </tr>
                                <?php endforeach ; ?>

                            <?php endif ; ?>

                        </tbody>
                   </table>
                </div>
            </div>

        </div>
    </div>
</body>
</html>